USE [levelup]
GO
SET IDENTITY_INSERT [dbo].[physical_activities] ON 

INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (1, N'aérobic', CAST(5.08 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (2, N'alpinisme', CAST(11.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (3, N'aviron', CAST(3.30 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (4, N'badmington', CAST(6.62 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (5, N'basketball (match)', CAST(9.70 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (6, N'bowling', CAST(2.40 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (7, N'boxe (entraînement)', CAST(9.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (8, N'boxe (match)', CAST(12.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (9, N'canoë (4 km/h)', CAST(3.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (10, N'canoë (6.5 km/h)', CAST(6.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (11, N'corde à sauter (modéré)', CAST(10.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (12, N'corde à sauter (intense)', CAST(12.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (13, N'course (escalier)', CAST(15.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (14, N'course (8 km/h)', CAST(8.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (15, N'course (10 km/h)', CAST(10.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (16, N'course (11 km/h)', CAST(11.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (17, N'course (12 km/h)', CAST(12.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (18, N'course (13 km/h)', CAST(13.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (19, N'course (14 km/h)', CAST(14.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (20, N'course (15 km/h)', CAST(15.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (21, N'course (16 km/h)', CAST(16.50 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (22, N'course (17 km/h)', CAST(18.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (23, N'cyclisme (léger)', CAST(4.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (24, N'cyclisme (modéré)', CAST(8.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (25, N'cyclisme (course)', CAST(12.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (26, N'danse (calme)', CAST(2.40 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (27, N'danse (intense)', CAST(6.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (28, N'escrime', CAST(6.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (29, N'football', CAST(8.60 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (30, N'golf', CAST(4.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (31, N'haltérophilie (léger)', CAST(4.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (32, N'haltérophilie (intense)', CAST(8.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (33, N'handball', CAST(10.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (34, N'hockey', CAST(8.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (35, N'jogging (8 km/h)', CAST(8.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (36, N'jogging (10 km/h)', CAST(10.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (37, N'judo', CAST(10.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (38, N'karate', CAST(10.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (39, N'kick boxing', CAST(10.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (40, N'lutte', CAST(6.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (41, N'marche à pied (3 km/h)', CAST(2.60 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (42, N'marche à pied (5 km/h)', CAST(3.50 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (43, N'marche à pied (6 km/h)', CAST(4.40 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (44, N'musculation (léger)', CAST(5.50 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (45, N'musculation (modéré)', CAST(8.40 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (46, N'musculation (intense)', CAST(11.20 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (47, N'natation (brasse coulée)', CAST(10.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (48, N'natation (papillon)', CAST(11.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (49, N'natation (dos crawlé)', CAST(8.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (50, N'natation (nage libre modérée)', CAST(8.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (51, N'natation (nage libre intense)', CAST(10.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (52, N'racketball', CAST(9.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (53, N'rameur', CAST(8.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (54, N'randonnée', CAST(6.80 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (55, N'randonnée (avec 5kg)', CAST(8.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (56, N'randonnée (avec 10kg)', CAST(8.80 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (57, N'randonnée (avec 15kg)', CAST(10.40 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (58, N'rugby', CAST(10.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (59, N'ski (descente)', CAST(6.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (60, N'ski de fond (léger)', CAST(6.80 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (61, N'ski de fond (modéré)', CAST(9.70 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (62, N'ski de fond (intense)', CAST(14.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (63, N'ski nautique', CAST(7.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (64, N'squash', CAST(9.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (65, N'stair climber (machine)', CAST(7.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (66, N'step aérobic', CAST(6.40 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (67, N'surf', CAST(3.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (68, N'taekwondo', CAST(10.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (69, N'tai chi', CAST(4.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (70, N'tennis (simple)', CAST(7.06 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (71, N'tennis (doubles)', CAST(6.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (72, N'volleyball (léger)', CAST(4.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (73, N'volleyball (match)', CAST(8.00 AS Numeric(5, 2)))
INSERT [dbo].[physical_activities] ([id], [name], [cal_per_kg_per_hour]) VALUES (74, N'yoga', CAST(4.00 AS Numeric(5, 2)))
SET IDENTITY_INSERT [dbo].[physical_activities] OFF

